---
title: "Week 2: Starting with R"
author: "UZH n UU: tested by Jonas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2: default
  bookdown::pdf_document2: default
bibliography: bibliography.bib
---

```{r load libraries, include=FALSE}
# install readr from CRAN
# install.packages("readr")
library(readr) # make sure your R has this library loaded, if not install it (see line above)
```

# Exercises for the R-Beginner - The fancy calculator

## Exercise 2
* from https://alexd106.github.io/intro2R/exercise_2.html
```{r myN, echo=FALSE, include=TRUE}
myNumber <- 12.43

# do some calculations
# natural log
log(myNumber)
```

```{r lg10, echo=TRUE, include=TRUE}
# log10
log10(myNumber)
```

# Session Information

```{r log2, echo=FALSE, include=TRUE}
# log2
log2(myNumber)
```


```{r square, echo=FALSE, include=TRUE}
sqrt(12.43)
```
```{r antilog, echo=FALSE, include=TRUE}
exp(12.43)
```



```{r area, echo=FALSE, include=TRUE}
radius <- 20 / 2
area_circle <- pi * radius^2
print(area_circle)
```
```{r root, echo=FALSE, include=TRUE}
result <- (14 * 0.51)^(1/3)
print(result)
```



```{r weight, echo=FALSE, include=TRUE}
# Create the weight vector
weight <- c(69, 62, 57, 59, 59, 64, 56, 66, 67, 66)

# Print the vector
print(weight)
```
```{r values weight, echo=FALSE, include=TRUE}
# Create the weight vector
weight <- c(69, 62, 57, 59, 59, 64, 56, 66, 67, 66)

# Calculate the mean (average)
mean_weight <- mean(weight)

# Calculate the variance
var_weight <- var(weight)

# Calculate the standard deviation
sd_weight <- sd(weight)

# Calculate the range (difference between max and min)
range_weight <- range(weight)  # Returns min and max values
range_diff <- max(weight) - min(weight)  # Calculates range

# Count the number of children (length of the vector)
num_children <- length(weight)

# Print the results
print(paste("Mean:", mean_weight))
print(paste("Variance:", var_weight))
print(paste("Standard Deviation:", sd_weight))
print(paste("Range:", range_diff))
print(paste("Number of children:", num_children))
```

```{r height, echo=FALSE, include=TRUE}
# Create the height vector
height <- c(112, 102, 83, 84, 99, 90, 77, 112, 133, 112)

# Summarize the height data
summary(height)

# Extract the height of the 2nd, 3rd, 9th, and 10th child
some_child <- height[c(2, 3, 9, 10)]
print(some_child)

# Extract all heights of children less than or equal to 99 cm
shorter_child <- height[height <= 99]
print(shorter_child)
```
```{r BMI, echo=FALSE, include=TRUE}
# Example weight (in kg) and height (in meters) vectors
weight <- c(69, 62, 57, 59, 59, 64, 56, 66, 67, 66)
height <- c(112, 102, 83, 84, 99, 90, 77, 112, 133, 112)

# Calculate BMI using vectorization
bmi <- weight / (height ^ 2)

# Print the BMI values
print(bmi)
```
```{r steps of 10, echo=FALSE, include=TRUE}
# Create a sequence from 0 to 1 in steps of 0.1
seq1 <- seq(0, 1, by = 0.1)

# Print the sequence
print(seq1)
```


```{r steps back to 1, echo=FALSE, include=TRUE}
# Create a sequence from 1 to 10 in steps of 0.5
seq2 <- seq(1, 10, by = 0.5)

# Reverse the sequence
seq2 <- rev(seq2)

# Print the sequence
print(seq2)
```
