---
title: "Excercise3_MathildeHatlem"
output: html_document
---

---
title: "Week 2: Starting with R"
author: "UZH n UU: tested by Jonas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2: default
  bookdown::pdf_document2: default
bibliography: bibliography.bib
---

```{r load libraries, include=FALSE}
# install readr from CRAN
# install.packages("readr")
library(readr) # make sure your R has this library loaded, if not install it (see line above)
```

# Exercises for the R-Beginner

## Exercise 3
### Part 5
```{r, echo=TRUE, include=TRUE}
mywhaledata <- read.table("/Users/mathildehatlem/OmicsInOncology_CPS341nBio435_FS25/week2/data4exercises/mywhaledata.tsv", header = TRUE, sep = "\t", stringsAsFactors = TRUE)
```
### Part 7
```{r, echo=TRUE, include=TRUE}
summary(mywhaledata)
```
### Part 9
```{r, echo=TRUE, include=TRUE}
deep_deep <- mywhaledata[mywhaledata$depth > 1200, ]
deep_deep

steep_steep <- mywhaledata[mywhaledata$gradient > 200, ]
steep_steep

low_noise <- mywhaledata[mywhaledata$water.noise == 'low', ]
low_noise

high_may <- mywhaledata[mywhaledata$water.noise == 'high' & mywhaledata$month == 'may', ]
high_may

```




## session
```{r sessionInfo, echo=FALSE, include=TRUE}
pander::pander(sessionInfo())
