---
title: "Week 2: Starting with R"
author: "UZH n UU: tested by Jonas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2: default
  bookdown::pdf_document2: default
bibliography: bibliography.bib
---

```{r load libraries, include=FALSE}
# install readr from CRAN
# install.packages("readr")
library(readr) # make sure your R has this library loaded, if not install it (see line above)
```

# Exercises for the R-Beginner - The fancy calculator

## Exercise 2
* from https://alexd106.github.io/intro2R/exercise_2.html

### Exercise 2.2
```{r myN, echo=TRUE, include=TRUE}
myNumber <- 12.43
# natural log
log(myNumber)
```

```{r lg10, echo=TRUE, include=TRUE}
# log10
log10(myNumber)
```

```{r lg2, echo=TRUE, include=TRUE}
# log2
log2(myNumber)
```

```{r sqrt, echo=TRUE, include=TRUE}
# square root
sqrt(myNumber)
```

```{r exp, echo=TRUE, include=TRUE}
# natural antilog
exp(myNumber)
```
### Exercise 2.3
```{r area, echo=TRUE, include=TRUE}
# area of the circle
radius <- 20/2
area_circle <- pi * radius^2
area_circle
```
### Exercise 2.4
```{r cube root, echo=TRUE, include=TRUE}
# cube root
product <- (14 * 0.51)^(1/3)
product
```
### Exercise 2.5
```{r vector, echo=TRUE, include=TRUE}
# vector
weight <- c(69, 62, 57, 59, 59, 64, 56, 66, 67, 66)
weight
```
### Exercise 2.6
```{r mean, echo=TRUE, include=TRUE}
# mean
weight <- c(69, 62, 57, 59, 59, 64, 56, 66, 67, 66)
mean(weight)
```

```{r variance, echo=TRUE, include=TRUE}
# variance
weight <- c(69, 62, 57, 59, 59, 64, 56, 66, 67, 66)
var(weight)
```

```{r standard deviation, echo=TRUE, include=TRUE}
# standard deviation
weight <- c(69, 62, 57, 59, 59, 64, 56, 66, 67, 66)
sd(weight)
```

```{r range, echo=TRUE, include=TRUE}
# range
weight <- c(69, 62, 57, 59, 59, 64, 56, 66, 67, 66)
range(weight)
```

```{r length, echo=TRUE, include=TRUE}
# length
weight <- c(69, 62, 57, 59, 59, 64, 56, 66, 67, 66)
length(weight)
```

```{r first 5 kids, echo=TRUE, include=TRUE}
# first five kids
weight <- c(69, 62, 57, 59, 59, 64, 56, 66, 67, 66)
first_five <- weight[c(1, 2, 3, 4, 5)]
first_five
```
### Exercise 2.7
```{r height, echo=TRUE, include=TRUE}
# height
height <- c(112, 102, 83, 84, 99, 90, 77, 112, 133, 112)
summary(height)
```

```{r some child, echo=TRUE, include=TRUE}
# some child
height <- c(112, 102, 83, 84, 99, 90, 77, 112, 133, 112)
some_child <- height[c(2, 3, 9, 10)]
some_child
```

```{r shorter child, echo=TRUE, include=TRUE}
# shorter child
height <- c(112, 102, 83, 84, 99, 90, 77, 112, 133, 112)
shorter_child <- height[height < 99]
shorter_child
```
### Exercise 2.8
```{r BMI, echo=TRUE, include=TRUE}
# shorter child
height <- c(112, 102, 83, 84, 99, 90, 77, 112, 133, 112)
height_meters <- height / 100
BMI <- weight / (height_meters^2)
BMI
```
# Session Information

```{r sessionInfo, echo=FALSE, include=TRUE}
pander::pander(sessionInfo())
```



