---
title: "Week 2: Starting with R"
author: "UZH n UU: tested by Jonas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2: default
  bookdown::pdf_document2: default
bibliography: bibliography.bib
---

```{r load libraries, include=FALSE}
# install readr from CRAN
# install.packages("readr")
library(readr) # make sure your R has this library loaded, if not install it (see line above)
```

# Exercises for the R-Beginner - The fancy calculator

## Exercise 2
* from https://alexd106.github.io/intro2R/exercise_2.html
```{r myN1, echo=TRUE, include=TRUE}
myNumber <- 12.43

# do some calculations
# natural log
log(myNumber)
```

```{r lg10, echo=TRUE, include=TRUE}
# log10
log10(myNumber)
```

```{r lg2, echo=TRUE, include=TRUE}
# log2
log2(myNumber)
```
```{r myN, echo=TRUE, include=TRUE}
# squareroot
sqrt(myNumber)
```
```{r myN2, echo=TRUE, include=TRUE}
#natural antilog 
exp(myNumber)
```

# Session Information

```{r sessionInfo, echo=TRUE, include=TRUE}
pander::pander(sessionInfo())
```
#Q3
```{r, echo=TRUE, include=TRUE}
#assign the radius
r <- 20/2
#area circle 
(area_circle <- pi*r^2)

```
#Q4
```{r, echo=TRUE, include=TRUE}
#cube root
result <- (14*0.51)^(1/3)
print (result)
```
#Q5
```{r, echo=TRUE, include=TRUE}
#create a vector
weight <- c(69,62,57,59,59,64,56,66,67,66)

#display the vector
print (weight)
```
#Q6
```{r, echo=TRUE, include=TRUE}
vec_mean <- mean (weight)
print(vec_mean)
var(weight)
sd (weight)
range(weight)
length(weight)
```
#Q6
```{r, echo=TRUE, include=TRUE}
first_five <- weight [1:5]
print (first_five)
```
#Q7

```{r, echo=TRUE, include=TRUE}
#create vector 
height <- c(112,102,83,84,99,90,77,112,133,112)
#summarize height data
summary(height)
#some children height 
some_child <-height[c(2,3,9,10)]
#shorter child 
shorter_child<-height[height<=99]
#display the vector
print(height)
print(some_child)
print(shorter_child)
```
#Q8

```{r, echo=TRUE, include=TRUE}
#bmi
weight <- c(69,62,57,59,59,64,56,66,67,66)
height <- c(112,102,83,84,99,90,77,112,133,112)
height_m <- height / 100  
bmi<-(weight/height_m^2)
print(bmi)
```

#Q9

```{r, echo=TRUE, include=TRUE}
seq1<-seq(from=0, to=1, by=0.1)
print(seq1)
```
#Q10
```{r, echo=TRUE, include=TRUE}
seq2<-rev(seq(from=1, to=10, by=0.5))
print(seq2)
```






