---
title: "Week 2: Starting with R"
author: "UZH n UU: tested by Jonas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2: default
  bookdown::pdf_document2: default
bibliography: bibliography.bib
---

```{r load libraries, include=FALSE}
# install readr from CRAN
# install.packages("readr")
library(readr) # make sure your R has this library loaded, if not install it (see line above)
```

# Exercises for the R-Beginner - The fancy calculator

## Exercise 3
* from https://alexd106.github.io/intro2R/exercise_3.html
##task 4 is reading 
##task 5
```{r myN, echo=FALSE, include=TRUE}
whale <- read.table ('../data4exercises/mywhaledata.tsv', header=TRUE)
whale 
```
##task 7
```{r , echo=FALSE, include=TRUE}
summary (whale)
#only number.whales is missing 1 value 
``` 
##task 9 
```{r , echo=TRUE, include=TRUE}
greaterdepth <- whale[whale$depth > 1200,]
greaterdepth
```

```{r , echo=TRUE, include=TRUE}
steep <- whale [whale$gradient > 200, ]
steep
``` 
```{r , echo=TRUE, include=TRUE}
silent <- whale [whale$water.noise == 'low', ]
silent
```
```{r , echo=TRUE, include=TRUE}
highmay <- whale [whale$month == 'May'& whale$water.noise == 'high',]
highmay
```
```{r , echo=TRUE, include=TRUE}
oktober <- whale [whale$month == 'October'& whale$water.noise == 'low' & whale$gradient > median(whale$gradient),]
oktober
```
```{r , echo=TRUE, include=TRUE}
latlon <-whale [whale$latitude >= 60 & whale$latitude <= 61 & whale$longitude >= -6 & whale$longitude <=-4,]
latlon
```

```{r , echo=TRUE, include=TRUE}
nomedium <- whale[whale$water.noise != 'medium',]
nomedium
```
##task 10
```{r , echo=TRUE, include=TRUE}
modifiedmedium <- whale [whale$gradient > median(whale$gradient),]
modifiedmedium
```
##task 11
```{r , echo=TRUE, include=TRUE}
deepspot <- whale[whale$depth > 1500 & whale$number.whales > mean (whale$number.whales, na.rm = TRUE),]
deepspot
```
