---
title: "Week 2: Starting with R"
author: "UZH n UU: tested by Jonas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2: default
  bookdown::pdf_document2: default
bibliography: bibliography.bib
---

```{r load libraries, include=FALSE}
# install readr from CRAN
# install.packages("readr")
library(readr) # make sure your R has this library loaded, if not install it (see line above)
```

# Exercises for the R-Beginner - The fancy calculator

## Exercise 2
* from https://alexd106.github.io/intro2R/exercise_2.html
```{r myN, echo=FALSE, include=TRUE}
myNumber <- 12.43

# do some calculations
# natural log
log(myNumber)
```

```{r lg10, echo=TRUE, include=TRUE}
# log10
log10(myNumber)
```
```{r, echo=TRUE, include=TRUE}
log2(myNumber)
```
```{r echo=TRUE, include=TRUE}
sqrt (myNumber)
```
```{r echo=TRUE, include=TRUE}
exp(myNumber)
```
##task 3
```{r echo=TRUE, include=TRUE}
area_circle <- (pi*20^2)
print(area_circle)
```
##task 5
```{r echo=TRUE, include=TRUE}
weight <- c(69, 62, 57, 59, 59, 64, 56, 66, 67, 66)
mean (weight)
var (weight)
sd(weight)
range(weight)
length(weight)

```
```{r echo=TRUE, include=TRUE}
weight <- c(69, 62, 57, 59, 59, 64, 56, 66, 67, 66)
first_five <- weight[1:5]

first_five
```
##task 7
```{r echo=TRUE, include=TRUE}
height <- c(112, 102, 83, 84, 99, 90, 77, 112, 133, 112)
summary (height)
```
```{r echo=TRUE, include=TRUE}
height <- c(112, 102, 83, 84, 99, 90, 77, 112, 133, 112)
some_height <- height [c(2, 3, 9, 10)]
some_height 
```
```{r echo=TRUE, include=TRUE}
height <- c(112, 102, 83, 84, 99, 90, 77, 112, 133, 112)
shorter_child <- height [3:7] 
shorter_child
```
```{r echo=TRUE, include=TRUE}
height <- c(112, 102, 83, 84, 99, 90, 77, 112, 133, 112)
meter_values <- height/100
print (meter_values)
```
##task 8
```{r echo=TRUE, include=TRUE}
BMI <- weight/meter_values 
BMI 
```

##task 9
```{r echo=TRUE, include=TRUE}
seq1 <- seq(from = 0, to = 1, by = 0.1)
seq1
``` 
##task 10
```{r echo=TRUE, include=TRUE}
seq2 <- seq(from = 1, to = 10, by = 0.5)
rev(seq2)
``` 
#Session Information

```{r sessionInfo, echo=FALSE, include=TRUE}
pander::pander(sessionInfo())
```


