---
title: "Week 2: Starting with R"
author: "UZH n UU: tested by Jonas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2: default
  bookdown::pdf_document2: default
bibliography: bibliography.bib
---

```{r load libraries, include=FALSE}
# install readr from CRAN
# install.packages("readr")
library(readr) # make sure your R has this library loaded, if not install it (see line above)
```

# Exercises for the R-Beginner - The fancy calculator

## Exercise 2
* from https://alexd106.github.io/intro2R/exercise_2.html

```{r, echo=TRUE, include=TRUE}
#whaledata exercise 3
whale <- read.table('../data4exercises/mywhaledata.tsv', header = TRUE)
#only number.whales is missing 1 value
#exercise 3.9 depth bigger than 1200
verydeep <- whale[depth>1200,]
verydeep
```

```{r, echo=TRUE, include=TRUE}
#exercise 3.9 water noise = low
silent <- whale[whale$water.noise =='low',]
silent
```

```{r, echo=TRUE, include=TRUE}
#exercise 3.9 gradient higher than 200
steep <- whale[whale$gradient>200,]
steep
```

```{r, echo=TRUE, include=TRUE}
#Exercise 3.9 month is may and the noise is high
highmay <- whale[whale$month == 'May'& whale$water.noise == 'high',]
highmay
```
```{r, echo=TRUE, include=TRUE}
#Exercise 3.9; month October, water noise low, gradient hgher than mean.
october <- whale[whale$month == 'October'& whale$water.noise == 'low' & whale$gradient>median(whale$gradient),]
october
```
```{r, echo=TRUE, include=TRUE}
#exercise 3.9 between lat 60-61 and lon -4 - -6
latlon <- whale[whale$latitude>=60 & whale$latitude<=61 & whale$longitude>=-6 & whale$longitude<=-4,]
lonlat <- whale%>%
    filter(between(whale$latitude, 60, 61) & between(whale$longitude, -6, -4))
lonlat
```
```{r, echo=TRUE, include=TRUE}
#exercise 9 exclude medium noise
nomed <- whale[whale$water.noise !='medium',]
nomed
```
```{r, echo=TRUE, include=TRUE}
#exercise 3.9 modify mean median
modmed <- whale[whale$gradient>median(whale$gradient),]
modmed
```
```{r, echo=TRUE, include=TRUE}
#exercise 3.10 depth and number of whales spotter troubleshooting.
deepspot <- whale[whale$depth > 1500 & whale$number.whales >mean(whale$number.whales, na.rm = TRUE),]
deepspot
```


# Session Information

```{r sessionInfo, echo=FALSE, include=TRUE}
pander::pander(sessionInfo())
```


